version: '3.4'
services:

  jenkins-dind:
    image: redpandaci/jenkins-dind:2.89.3
    privileged: true
    tty: true
    ports:
      - 8081:8080
    environment: 
      - JENKINS_USER=CHANGE
      - JENKINS_PASS=CHANGE
    volumes:
      - /var/containers/jenkins:/root/.jenkins
